### ISSUE TITLE
Add support for multiple logos and update logos.

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/CakeContrib.Guidelines#136]
Logos will be updated in https://github.com/cake-contrib/graphics/pull/2

**Comment by Jericho** [comment]
AddinDiscoverer as been updated to support these new icons as well (I call them the "fancy" icons!!!).

As you can see below, the discoverer is now capable of detecting that 11 addins are using one of the fancy icons and 6 are using a custom icon instead of reporting that 17 addins are using a "custom" icon:
![image](https://user-images.githubusercontent.com/112710/115963485-7dd13880-a4ed-11eb-9c6d-297c7bf42f89.png)

This information is also reflected in the Excel report at the individual addin level. For example, the discoverer was able to detect that Nil's Cake.7zip addin is using a "fancy" icon:
![image](https://user-images.githubusercontent.com/112710/115963585-f59f6300-a4ed-11eb-86fb-2595658749fa.png)
